In [1]:
import pandas as pd

df = pd.read_csv("../data/raw/retail_store_inventory.csv")

df.head()

,Date,Store ID,Product ID,Category,Region,Inventory Level,Units Sold,Units Ordered,Demand Forecast,Price
0,2022-01-01,S001,P0001,Groceries,North,231,127,55,135.47,33.50
1,2022-01-01,S001,P0002,Toys,South,204,150,66,144.04,63.01
2,2022-01-01,S001,P0003,Toys,West,102,65,51,74.02,27.99
3,2022-01-01,S001,P0004,Toys,North,469,61,164,62.18,32.72
4,2022-01-01,S001,P0005,Electronics,East,166,14,135,9.26,73.64

In [2]:
df.shape

(73100, 10)

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 73100 entries, 0 to 73099
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Date             73100 non-null  str
 1   Store ID         73100 non-null  str
 2   Product ID       73100 non-null  str
 3   Category         73100 non-null  str
 4   Region           73100 non-null  str
 5   Inventory Level  73100 non-null  int64
 6   Units Sold       73100 non-null  int64
 7   Units Ordered    73100 non-null  int64
 8   Demand Forecast  73100 non-null  float64
 9   Price            73100 non-null  float64
dtypes: float64(2), int64(3), str(5)
memory usage: 5.6 MB

In [4]:
df.isnull().sum()

Date               0
Store ID           0
Product ID         0
Category           0
Region             0
Inventory Level    0
Units Sold         0
Units Ordered      0
Demand Forecast    0
Price              0
dtype: int64

In [5]:

# Check whether each store-product combination
# has repeated observations over time.

print("Dataset columns:")
print(df.columns.tolist())

print("\nNumber of unique dates:", df["Date"].nunique())
print("Number of stores:", df["Store ID"].nunique())
print("Number of products:", df["Product ID"].nunique())

print("\nRepeated store-product-date records:")
print(
    df.duplicated(
        subset=["Date", "Store ID", "Product ID"]
    ).sum()
)

print("\nPrice summary:")
print(df["Price"].describe())

print("\nPrice variation by store and product:")
print(
    df.groupby(["Store ID", "Product ID"])["Price"]
    .nunique()
    .describe()
)

Dataset columns:
['Date', 'Store ID', 'Product ID', 'Category', 'Region', 'Inventory Level', 'Units Sold', 'Units Ordered', 'Demand Forecast', 'Price']

Number of unique dates: 731
Number of stores: 5
Number of products: 20

Repeated store-product-date records:
0

Price summary:
count    73100.000000
mean        55.135108
std         26.021945
min         10.000000
25%         32.650000
50%         55.050000
75%         77.860000
max        100.000000
Name: Price, dtype: float64

Price variation by store and product:
count    100.00000
mean     700.99000
std        4.99999
min      687.00000
25%      698.00000
50%      701.00000
75%      705.00000
max      715.00000
Name: Price, dtype: float64

In [6]:

sales = pd.read_csv("../data/raw/sales_data.csv")

print("Shape:", sales.shape)
print("\nColumns:")
print(sales.columns.tolist())

print("\nFirst 5 rows:")
display(sales.head())

print("\nMissing values:")
print(sales.isnull().sum())

Shape: (76000, 16)

Columns:
['Date', 'Store ID', 'Product ID', 'Category', 'Region', 'Inventory Level', 'Units Sold', 'Units Ordered', 'Price', 'Discount', 'Weather Condition', 'Promotion', 'Competitor Pricing', 'Seasonality', 'Epidemic', 'Demand']

First 5 rows:

,Date,Store ID,Product ID,Category,Region,Inventory Level,Units Sold,Units Ordered,Price,Discount,Weather Condition,Promotion,Competitor Pricing,Seasonality,Epidemic,Demand
0,2022-01-01,S001,P0001,Electronics,North,195,102,252,72.72,5,Snowy,0,85.73,Winter,0,115
1,2022-01-01,S001,P0002,Clothing,North,117,117,249,80.16,15,Snowy,1,92.02,Winter,0,229
2,2022-01-01,S001,P0003,Clothing,North,247,114,612,62.94,10,Snowy,1,60.08,Winter,0,157
3,2022-01-01,S001,P0004,Electronics,North,139,45,102,87.63,10,Snowy,0,85.19,Winter,0,52
4,2022-01-01,S001,P0005,Groceries,North,152,65,271,54.41,0,Snowy,0,51.63,Winter,0,59

Missing values:
Date                  0
Store ID              0
Product ID            0
Category              0
Region                0
Inventory Level       0
Units Sold            0
Units Ordered         0
Price                 0
Discount              0
Weather Condition     0
Promotion             0
Competitor Pricing    0
Seasonality           0
Epidemic              0
Demand                0
dtype: int64

In [7]:

print("Dataset shape:", sales.shape)

print("\nColumn names:")
print(sales.columns.tolist())

print("\nFirst 5 rows:")
display(sales.head())

print("\nData types:")
print(sales.dtypes)

Dataset shape: (76000, 16)

Column names:
['Date', 'Store ID', 'Product ID', 'Category', 'Region', 'Inventory Level', 'Units Sold', 'Units Ordered', 'Price', 'Discount', 'Weather Condition', 'Promotion', 'Competitor Pricing', 'Seasonality', 'Epidemic', 'Demand']

First 5 rows:

,Date,Store ID,Product ID,Category,Region,Inventory Level,Units Sold,Units Ordered,Price,Discount,Weather Condition,Promotion,Competitor Pricing,Seasonality,Epidemic,Demand
0,2022-01-01,S001,P0001,Electronics,North,195,102,252,72.72,5,Snowy,0,85.73,Winter,0,115
1,2022-01-01,S001,P0002,Clothing,North,117,117,249,80.16,15,Snowy,1,92.02,Winter,0,229
2,2022-01-01,S001,P0003,Clothing,North,247,114,612,62.94,10,Snowy,1,60.08,Winter,0,157
3,2022-01-01,S001,P0004,Electronics,North,139,45,102,87.63,10,Snowy,0,85.19,Winter,0,52
4,2022-01-01,S001,P0005,Groceries,North,152,65,271,54.41,0,Snowy,0,51.63,Winter,0,59

Data types:
Date                      str
Store ID                  str
Product ID                str
Category                  str
Region                    str
Inventory Level         int64
Units Sold              int64
Units Ordered           int64
Price                 float64
Discount                int64
Weather Condition         str
Promotion               int64
Competitor Pricing    float64
Seasonality               str
Epidemic                int64
Demand                  int64
dtype: object

In [8]:

print("Shape:", sales.shape)
display(sales.head())

Shape: (76000, 16)

,Date,Store ID,Product ID,Category,Region,Inventory Level,Units Sold,Units Ordered,Price,Discount,Weather Condition,Promotion,Competitor Pricing,Seasonality,Epidemic,Demand
0,2022-01-01,S001,P0001,Electronics,North,195,102,252,72.72,5,Snowy,0,85.73,Winter,0,115
1,2022-01-01,S001,P0002,Clothing,North,117,117,249,80.16,15,Snowy,1,92.02,Winter,0,229
2,2022-01-01,S001,P0003,Clothing,North,247,114,612,62.94,10,Snowy,1,60.08,Winter,0,157
3,2022-01-01,S001,P0004,Electronics,North,139,45,102,87.63,10,Snowy,0,85.19,Winter,0,52
4,2022-01-01,S001,P0005,Groceries,North,152,65,271,54.41,0,Snowy,0,51.63,Winter,0,59

In [9]:

print("Dataset shape:", sales.shape)

print("\nColumn names:")
print(sales.columns.tolist())

print("\nMissing values:")
print(sales.isnull().sum())

print("\nUnique values in key columns:")
for col in ["Price", "Discount", "Promotion", "Competitor Pricing", "Units Sold"]:
    print(f"{col}: {sales[col].nunique()} unique values")

Dataset shape: (76000, 16)

Column names:
['Date', 'Store ID', 'Product ID', 'Category', 'Region', 'Inventory Level', 'Units Sold', 'Units Ordered', 'Price', 'Discount', 'Weather Condition', 'Promotion', 'Competitor Pricing', 'Seasonality', 'Epidemic', 'Demand']

Missing values:
Date                  0
Store ID              0
Product ID            0
Category              0
Region                0
Inventory Level       0
Units Sold            0
Units Ordered         0
Price                 0
Discount              0
Weather Condition     0
Promotion             0
Competitor Pricing    0
Seasonality           0
Epidemic              0
Demand                0
dtype: int64

Unique values in key columns:
Price: 15396 unique values
Discount: 6 unique values
Promotion: 2 unique values
Competitor Pricing: 15963 unique values
Units Sold: 330 unique values

In [10]:

print("Dataset shape:", sales.shape)

print("\nColumn names:")
print(sales.columns.tolist())

print("\nMissing values:")
print(sales.isnull().sum())

print("\nUnique values in key columns:")
for col in ["Price", "Discount", "Promotion", "Competitor Pricing", "Units Sold"]:
    print(f"{col}: {sales[col].nunique()} unique values")

Dataset shape: (76000, 16)

Column names:
['Date', 'Store ID', 'Product ID', 'Category', 'Region', 'Inventory Level', 'Units Sold', 'Units Ordered', 'Price', 'Discount', 'Weather Condition', 'Promotion', 'Competitor Pricing', 'Seasonality', 'Epidemic', 'Demand']

Missing values:
Date                  0
Store ID              0
Product ID            0
Category              0
Region                0
Inventory Level       0
Units Sold            0
Units Ordered         0
Price                 0
Discount              0
Weather Condition     0
Promotion             0
Competitor Pricing    0
Seasonality           0
Epidemic              0
Demand                0
dtype: int64

Unique values in key columns:
Price: 15396 unique values
Discount: 6 unique values
Promotion: 2 unique values
Competitor Pricing: 15963 unique values
Units Sold: 330 unique values

In [11]:

print("Dataset shape:", sales.shape)
print("\nAll columns:")
print(sales.columns.tolist())

print("\nData types:")
print(sales.dtypes)

print("\nFirst 5 rows:")
display(sales.head())

print("\nDuplicate rows:", sales.duplicated().sum())

print(
    "Duplicate date-store-product records:",
    sales.duplicated(
        subset=["Date", "Store ID", "Product ID"]
    ).sum()
)

Dataset shape: (76000, 16)

All columns:
['Date', 'Store ID', 'Product ID', 'Category', 'Region', 'Inventory Level', 'Units Sold', 'Units Ordered', 'Price', 'Discount', 'Weather Condition', 'Promotion', 'Competitor Pricing', 'Seasonality', 'Epidemic', 'Demand']

Data types:
Date                      str
Store ID                  str
Product ID                str
Category                  str
Region                    str
Inventory Level         int64
Units Sold              int64
Units Ordered           int64
Price                 float64
Discount                int64
Weather Condition         str
Promotion               int64
Competitor Pricing    float64
Seasonality               str
Epidemic                int64
Demand                  int64
dtype: object

First 5 rows:

,Date,Store ID,Product ID,Category,Region,Inventory Level,Units Sold,Units Ordered,Price,Discount,Weather Condition,Promotion,Competitor Pricing,Seasonality,Epidemic,Demand
0,2022-01-01,S001,P0001,Electronics,North,195,102,252,72.72,5,Snowy,0,85.73,Winter,0,115
1,2022-01-01,S001,P0002,Clothing,North,117,117,249,80.16,15,Snowy,1,92.02,Winter,0,229
2,2022-01-01,S001,P0003,Clothing,North,247,114,612,62.94,10,Snowy,1,60.08,Winter,0,157
3,2022-01-01,S001,P0004,Electronics,North,139,45,102,87.63,10,Snowy,0,85.19,Winter,0,52
4,2022-01-01,S001,P0005,Groceries,North,152,65,271,54.41,0,Snowy,0,51.63,Winter,0,59

Duplicate rows: 0
Duplicate date-store-product records: 0

In [12]:

print("Shape:", sales.shape)

print("\nColumns:")
print(sales.columns.tolist())

print("\nDuplicate rows:", sales.duplicated().sum())

print("\nDuplicate date-store-product records:",
      sales.duplicated(
          subset=["Date", "Store ID", "Product ID"]
      ).sum())

print("\nFirst 5 rows:")
display(sales.head())

Shape: (76000, 16)

Columns:
['Date', 'Store ID', 'Product ID', 'Category', 'Region', 'Inventory Level', 'Units Sold', 'Units Ordered', 'Price', 'Discount', 'Weather Condition', 'Promotion', 'Competitor Pricing', 'Seasonality', 'Epidemic', 'Demand']

Duplicate rows: 0

Duplicate date-store-product records: 0

First 5 rows:

,Date,Store ID,Product ID,Category,Region,Inventory Level,Units Sold,Units Ordered,Price,Discount,Weather Condition,Promotion,Competitor Pricing,Seasonality,Epidemic,Demand
0,2022-01-01,S001,P0001,Electronics,North,195,102,252,72.72,5,Snowy,0,85.73,Winter,0,115
1,2022-01-01,S001,P0002,Clothing,North,117,117,249,80.16,15,Snowy,1,92.02,Winter,0,229
2,2022-01-01,S001,P0003,Clothing,North,247,114,612,62.94,10,Snowy,1,60.08,Winter,0,157
3,2022-01-01,S001,P0004,Electronics,North,139,45,102,87.63,10,Snowy,0,85.19,Winter,0,52
4,2022-01-01,S001,P0005,Groceries,North,152,65,271,54.41,0,Snowy,0,51.63,Winter,0,59

In [13]:
print("Dataset shape:", sales.shape)

print("\nAll columns:")
print(sales.columns.tolist())

print("\nFirst 5 rows:")
display(sales.head())

print("\nNumeric column summary:")
display(sales.describe().T)

Dataset shape: (76000, 16)

All columns:
['Date', 'Store ID', 'Product ID', 'Category', 'Region', 'Inventory Level', 'Units Sold', 'Units Ordered', 'Price', 'Discount', 'Weather Condition', 'Promotion', 'Competitor Pricing', 'Seasonality', 'Epidemic', 'Demand']

First 5 rows:

,Date,Store ID,Product ID,Category,Region,Inventory Level,Units Sold,Units Ordered,Price,Discount,Weather Condition,Promotion,Competitor Pricing,Seasonality,Epidemic,Demand
0,2022-01-01,S001,P0001,Electronics,North,195,102,252,72.72,5,Snowy,0,85.73,Winter,0,115
1,2022-01-01,S001,P0002,Clothing,North,117,117,249,80.16,15,Snowy,1,92.02,Winter,0,229
2,2022-01-01,S001,P0003,Clothing,North,247,114,612,62.94,10,Snowy,1,60.08,Winter,0,157
3,2022-01-01,S001,P0004,Electronics,North,139,45,102,87.63,10,Snowy,0,85.19,Winter,0,52
4,2022-01-01,S001,P0005,Groceries,North,152,65,271,54.41,0,Snowy,0,51.63,Winter,0,59

Numeric column summary:

,count,mean,std,min,25%,50%,75%,max
Inventory Level,76000.0,301.062842,226.510161,0.00,136.0000,227.0,408.0000,2267.00
Units Sold,76000.0,88.827316,43.994525,0.00,58.0000,84.0,114.0000,426.00
Units Ordered,76000.0,89.090645,162.404627,0.00,0.0000,0.0,121.0000,1616.00
Price,76000.0,67.726028,39.377899,4.74,31.9975,64.5,95.8300,228.03
Discount,76000.0,9.087039,7.475781,0.00,5.0000,10.0,10.0000,25.00
Promotion,76000.0,0.328947,0.469834,0.00,0.0000,0.0,1.0000,1.00
Competitor Pricing,76000.0,69.454029,40.943818,4.29,32.6200,65.7,97.9325,261.22
Epidemic,76000.0,0.200000,0.400003,0.00,0.0000,0.0,0.0000,1.00
Demand,76000.0,104.317158,46.964801,4.00,71.0000,100.0,133.0000,430.00

In [14]:
print("Rows and columns:", sales.shape)

print("\nDuplicate rows:", sales.duplicated().sum())

print("\nDate range:")
print(sales["Date"].min(), "to", sales["Date"].max())

print("\nUnique stores:", sales["Store ID"].nunique())
print("Unique products:", sales["Product ID"].nunique())

print("\nRows per date:")
print(sales.groupby("Date").size().describe())

Rows and columns: (76000, 16)

Duplicate rows: 0

Date range:
2022-01-01 to 2024-01-30

Unique stores: 5
Unique products: 20

Rows per date:
count    760.0
mean     100.0
std        0.0
min      100.0
25%      100.0
50%      100.0
75%      100.0
max      100.0
dtype: float64

In [15]:
print("Price and Units Sold correlation:")
print(sales["Price"].corr(sales["Units Sold"]))

print("\nDiscount and Units Sold correlation:")
print(sales["Discount"].corr(sales["Units Sold"]))

print("\nAverage units sold by promotion:")
display(sales.groupby("Promotion")["Units Sold"].agg(["mean", "median", "count"]))

print("\nAverage units sold by discount level:")
display(sales.groupby("Discount")["Units Sold"].mean().sort_index())

Price and Units Sold correlation:
-0.01450627574461673

Discount and Units Sold correlation:
0.18352343298248597

Average units sold by promotion:

                 mean  median  count
Promotion
0           81.833314    78.0  51000
1          103.095080    98.0  25000

Average units sold by discount level:

Discount
0      81.574156
5      81.694763
10     87.657953
15    102.878463
20    103.774834
25    103.587914
Name: Units Sold, dtype: float64

In [16]:
features = [
    "Price",
    "Discount",
    "Promotion",
    "Competitor Pricing",
    "Demand",
    "Units Sold"
]

display(sales[features].corr().round(3))

,Price,Discount,Promotion,Competitor Pricing,Demand,Units Sold
Price,1.000,-0.094,-0.043,0.977,-0.023,-0.015
Discount,-0.094,1.000,0.784,-0.092,0.225,0.184
Promotion,-0.043,0.784,1.000,-0.041,0.283,0.227
Competitor Pricing,0.977,-0.092,-0.041,1.000,-0.023,-0.014
Demand,-0.023,0.225,0.283,-0.023,1.000,0.833
Units Sold,-0.015,0.184,0.227,-0.014,0.833,1.000